### PR TITLE
Fix fallback for numeric values

### LINKED ISSUE #221: Fallback expressions don't work when first is numeric
I'm trying to calculate height of an element based on the viewport height using `vh` units and fallback to the actual viewport height I'm injecting into the component as `height` property:

```javascript
    let backgroundStyle = {
      height: [`${height - headerHeight}px`, `calc(100vh - ${headerHeight}px)`]
    }
```

However, my component gets rendered with the following style
```css
height: 343px,calc(100vh - 64px)
```

packages:
```javascript
    "react": "0.13.3",
    "radium": "0.13.0"
```

I'm getting this CSS both on the server and on the client.

Interestingly enough, if I switch the order of the values:

```javascript
height: [`calc(100vh - ${headerHeight}px)`, `${height - headerHeight}px`]
```

I'm only getting the following CSS:

```css
height: calc(100vh - 64px)
```

### PR DESCRIPTION
**Pull request by ianobermiller**
Fixes #221, fallback when first value is a number. Also needs to add px
to non-unitless properties so the value checks can pass, otherwise
`[‘calc(…)’, 400]` would end up with calc, even if calc wasn’t
supported.

### CODE REVIEW

File: modules/prefixer.js [hunk 1]
```diff
@@ -127,13 +161,36 @@ var getPrefixedPropertyName = function (property) {
   return prefixedPropertyCache[property] = workingProperty;
 };
 
-var _getPrefixedValue = function (property, value, originalProperty) {
-  // don't test numbers or numbers with units (e.g. 10em)
+// React is planning to deprecate adding px automatically
+// (https://github.com/facebook/react/issues/1873), and if they do, this
```
Comment (alexlande) [inline modules/prefixer.js]: Wasn't aware of that. Cool.

**Comment by alexlande** [comment]
Little linty. :shipit:
